name: Deploy update

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH, update .env and backend server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/dot-pablomag/server
            sudo git pull
            sudo rm .env
            sudo touch .env
            sudo bash -c "echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env"
            sudo bash -c "echo API_URL=${{ secrets.API_URL }} >> .env"
            sudo bash -c "echo API_URI=${{ secrets.API_URI }} >> .env"
            sudo bash -c "echo API_PORT=${{ secrets.API_PORT }} >> .env"
            sudo bash -c "echo API_SECRET='`echo ${{ secrets.API_SECRET }} | base64 --decode`' >> .env"
            sudo bash -c "echo CLIENT_URL=${{ secrets.CLIENT_URL }} >> .env"
            sudo bash -c "echo IMG_SERVICE_URL=${{ secrets.IMG_SERVICE_URL }} >> .env"
            sudo bash -c "echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env"
            sudo bash -c "echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .env"
            sudo bash -c "echo REDIS_PASS=${{ secrets.REDIS_PASS }} >> .env"
            sudo bash -c "echo DB_CONNECTION='`echo ${{ secrets.DB_CONNECTION }} | base64 --decode`' >> .env"
            sudo bash -c "echo DB_USER=${{ secrets.DB_USER }} >> .env"
            sudo bash -c "echo DB_PASS='`echo ${{ secrets.DB_PASS }} | base64 --decode`' >> .env"
            sudo bash -c "echo GOOGLE_CLIENT_ID='`echo ${{ secrets.GOOGLE_CLIENT_ID }} | base64 --decode`' >> .env"
            sudo bash -c "echo ACCEPT_NEW_USERS=${{ secrets.ACCEPT_NEW_USERS }} >> .env"
            sudo yarn install
            sudo yarn build
            sudo yarn sass
            pm2 restart pm2.config.js
